### PR TITLE
End-state deviates from goal state

### LINKED ISSUE #531: Connect stage: incompatible end and start state marked as valid
This might be related to #405.

On some of my task solutions, I get incompatible end and start robot state that manages to be valid. I can clearly see the discontinuous joints from one stage to the other. I can replicate the bug quite easily on my setup. Latest MTC commit [a905572](https://github.com/ros-planning/moveit_task_constructor/commit/a90557279ca306fc30d39ec463af401022314b17) with MoveIt [8f39ef7](https://github.com/ros-planning/moveit/commit/8f39ef78bcae5940f5aad097c3c2fd4a4667b224) (same error on a 3 month old commit).

When executing the solution through the `move_group/ExecuteTaskSolutionCapability`, you can clearly see that something is wrong between stages with the discontinuous joint positions. This is shown below.

Just another though, shouldn't the execution stop because of the large position error between subtrajectory msgs? Maybe it sends the full trajectory in one go.

https://github.com/ros-planning/moveit_task_constructor/assets/32679594/3a089556-c2d7-4098-9d11-533283601d29

Discontinuous joint positions from one stage to the other.
image

### PR DESCRIPTION
**Pull request by captain-yoshi**
This fixes #531 but may not fix the actual problem, e.g. it may be the planner that silently fails or something else in the framework.

I just validate the last trajectory waypoint with the goal in the `ConnectStage`. If there is a deviation, the solution is marked as failed and a comment is set. I'm pretty sure you can optimize some of the code ;)

---

On a side note, I had to make sure that the joints where compared correctly (-pi = pi). Currently, when comparing joint position in the [Connect::compatible](https://github.com/ros-planning/moveit_task_constructor/blob/master/core/src/stages/connect.cpp#L124-L125) method, this is not checked. You might reject some valid solutions, e.g the IK solver gives some joint positions in a negative defined angle versus the RobotState who may have a positive defined angle.

Solution 1 et 3 are valid but not 2 and 4.

image

### CODE REVIEW

File: core/src/stages/connect.cpp [hunk 1]
```diff
@@ -132,6 +134,51 @@ bool Connect::compatible(const InterfaceState& from_state, const InterfaceState&
...
+		Eigen::Map<const Eigen::VectorXd> positions_goal(goal_state.getJointPositions(jm), num);
+		Eigen::Map<const Eigen::VectorXd> positions_last_waypoint(
+		    trajectory->getWayPoint(waypoint_count - 1).getJointPositions(jm), num);
+
+		double min_distance;
+		for (std::size_t i = 0; i < num; ++i) {
+			if (jm->getType() == robot_state::JointModel::REVOLUTE)
+				min_distance = angles::shortest_angular_distance(positions_last_waypoint[i], positions_goal[i]);
+			else
+				min_distance = positions_last_waypoint[i], positions_goal[i];
```
Comment (rhaschke) [inline core/src/stages/connect.cpp:162]: I guess you want to compute the joint difference:
```suggestion
				min_distance = std::abs(positions_last_waypoint[i] -  positions_goal[i]);
```

File: core/src/stages/connect.cpp [hunk 2]
```diff
@@ -132,6 +134,51 @@ bool Connect::compatible(const InterfaceState& from_state, const InterfaceState&
...
+
+			ROS_DEBUG_STREAM_NAMED("Connect",
+			                       "angular deviation: " << min_distance << " between trajectory last waypoint and goal.");
+
+			if (std::abs(min_distance) > 1e-4) {
```
Comment (rhaschke) [inline core/src/stages/connect.cpp:167]: The magic number 1e-4 should be configurable, e.g. via a stage property.

**Review by rhaschke — COMMENTED** [review]
Reading your solution to #531, I think that this is not related to incompatible start and end states: What you check is that the end-state actually reaches the goal state.
I think, your issue is a duplicate of #485, which was caused by a bug in MoveIt2.
Are you using MoveIt1 or MoveIt2? If you were using MoveIt1, it would be great if you could setup a failing unittest for your issue. Then, I can search for the underlying problem instead of applying cosmetic corrections :wink:

**Comment by captain-yoshi** [comment]
> What you check is that the end-state actually reaches the goal state.

Yes ! Changed the title.

> This fixes https://github.com/ros-planning/moveit_task_constructor/issues/531 but may not fix the actual problem, e.g. it may be the planner that silently fails or something else in the framework.

Just found the culprit. Even though LIN Pilz receives a JointConstraint, it will compute the [FK](https://github.com/ros-planning/moveit/blob/master/moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator_lin.cpp#L100) to compute the goal pose. Currently the LIN planner only plans from a [cartesian goal](https://github.com/ros-planning/moveit/blob/master/moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator_lin.cpp#L147). Will create an issue in MoveIt.

Not tested but I'm pretty sure I could recreate the problem by changing the demo pick and place and replacing this [line](https://github.com/ros-planning/moveit_task_constructor/blob/master/demo/src/pick_place_task.cpp#L219) with the LIN Pilz planner. Or would you prefer a unit-test in MoveIt ?

For testing this PR, is there a way to fake a planner response that would offset the goal state outside the threshold limits ?

**Comment by captain-yoshi** [comment]
To replicate this error, just use this mtc fork [captain-yoshi/moveit_task_constructor/tree/trigger-error-532](https://github.com/captain-yoshi/moveit_task_constructor/tree/trigger-error-532) and start the pick & place demo. This includes the validation in this PR.

You should see that it's failing and that for some solution the end-state does not match the goal-state.

image

**Comment by captain-yoshi** [comment]
After reading more on the [Pilz LIN](https://ros-planning.github.io/moveit_tutorials/doc/pilz_industrial_motion_planner/pilz_industrial_motion_planner.html#the-lin-motion-command) planner, it generates linear Cartesian trajectory between goal and start poses.

The solution would be to feed the joint constraint goal instead of redoing an IK.

**Comment by rhaschke** [comment]
Yes, the Pilz planner performs linear interpolation in Cartesian space. If you want to perform linear interpolation in joint space, there is the `JointInterpolationPlanner` in MTC available for this.

> Not tested but I'm pretty sure I could recreate the problem by changing the demo pick and place and replacing this [line](https://github.com/ros-planning/moveit_task_constructor/blob/master/demo/src/pick_place_task.cpp#L219) with the LIN Pilz planner. Or would you prefer a unit-test in MoveIt ?

So you claim, that the Pilz planner generates incomplete trajectories, which are considered to be valid by MTC?
Please create a unit test in MTC triggering exactly this issue. Thanks.
 
> For testing this PR, is there a way to fake a planner response that would offset the goal state outside the threshold limits?

Why would you like to do so? If a planner behaves like that, this planner is buggy and should get fixed.

File: core/src/stages/connect.cpp [hunk 3]
```diff
@@ -132,10 +136,57 @@ bool Connect::compatible(const InterfaceState& from_state, const InterfaceState&
...
+			continue;
+
+		Eigen::Map<const Eigen::VectorXd> positions_goal(goal_state.getJointPositions(jm), num);
+		Eigen::Map<const Eigen::VectorXd> positions_last_waypoint(
+		    trajectory->getWayPoint(waypoint_count - 1).getJointPositions(jm), num);
+
+		double min_distance;
+		for (std::size_t i = 0; i < num; ++i) {
+			if (jm->getType() == robot_state::JointModel::REVOLUTE)
+				min_distance = angles::shortest_angular_distance(positions_last_waypoint[i], positions_goal[i]);
```
Comment (rhaschke) [inline core/src/stages/connect.cpp:163]: You must not use `angles::shortest_angular_distance` here, as we need to reach the _exact_ goal state - subsequent stages rely on this fact!

**Review by rhaschke — CHANGES_REQUESTED** [review]
I see the need for this PR. Some planners, like Pilz or MTC's Cartesian interpolation, may not reach the exact goal state, although the Cartesian pose matches.
See the comment below to address before merging.

**Comment by captain-yoshi** [comment]
> I see the need for this PR. Some planners, like Pilz or MTC's Cartesian interpolation, may not reach the exact goal state, although the Cartesian poses match.

Exactly ! This is necessary to be able to use such planners. Furthermore, it can catch errors in other planners, e.g. #485. Finally, it guards against the `move_group/ExecuteTaskSolutionCapability` which seems to shoot the hole trajectory without doing any validation against the end state and the start state of sub-trajectories.

File: core/src/stages/connect.cpp (hunk 3 above)
Comment (captain-yoshi) [reply core/src/stages/connect.cpp:163]: Hum... I'm pretty sure it removed valid solutions... Will investigate more and report back soon.

**Comment by rhaschke** [comment]
> it guards against the `move_group/ExecuteTaskSolutionCapability` which seems to shoot the hole trajectory without doing any validation against the end state and the start state of sub-trajectories.

The discontinuity doesn't happen between the end-state and start-state of to consecutive trajectories but between the next-to-last and last state of the Connect trajectories. Thus, MoveIt's task execution cannot guard against this discontinuity.

**Comment by rhaschke** [comment]
I pushed a simplifying commit, using `RobotState::distance()` to compute the joint-space distance between the two states. No need to reimplement the wheel ;-)

**Comment by captain-yoshi** [comment]
All good on my end :) Great optimization by the way :1st_place_medal:

File: core/src/stages/connect.cpp (hunk 3 above)
Comment (rhaschke) [reply core/src/stages/connect.cpp]: We cannot accept equality up to multiples to 360°. The goal state needs to be reached exactly. Otherwise subsequent stages will run into trouble because they relied on a different start state.
